services:
  _defaults:
    public: true

  PrestaShop\Module\OrderFeatures\Adapter\Order\Repository\OrderRepository:
    autoconfigure: true
    autowire: true
    arguments: ["@doctrine.dbal.default_connection", "%database_prefix%"]

  decorated_order_controller:
    class: PrestaShop\Module\OrderFeatures\Controller\Admin\Sell\Order\OrderController
    decorates: PrestaShopBundle\Controller\Admin\Sell\Order\OrderController
    arguments: ["@decorated_order_controller.inner"]
    autowire: true
    autoconfigure: true
    calls: [[setLogger, ['@logger']]]
    tags: ['controller.service_arguments'] 

  prestashop.module.orderfeatures.core.grid.definition.factory.order:
    class: PrestaShop\Module\OrderFeatures\Core\Grid\Definition\Factory\OrderGridDefinitionFactory
    decorates: prestashop.core.grid.definition.factory.order
    autoconfigure: true
    autowire: true
    arguments: ["@prestashop.module.orderfeatures.core.grid.definition.factory.order.inner", "@prestashop.core.hook.dispatcher"]
    calls: [[setTranslator, ['@translator']]]

  PrestaShop\Module\OrderFeatures\Adapter\Order\CommandHandler\DeleteOrderHandler:
    public: false
    autowire: true
    autoconfigure: true

  PrestaShop\Module\OrderFeatures\Adapter\Order\CommandHandler\BulkDeleteOrderHandler:
    public: false
    autowire: true
    autoconfigure: true

  PrestaShop\Module\OrderFeatures\Adapter\Order\OrderDeleter:
    public: false
    autowire: true

  PrestaShop\Module\OrderFeatures\Form\Admin\Configure\ShopParameters\OrderStates\OrderStateType:
    decorates: PrestaShopBundle\Form\Admin\Configure\ShopParameters\OrderStates\OrderStateType
    arguments:
      $locales: "@=service('prestashop.adapter.legacy.context').getLanguages()"
      $themeCatalog: '@prestashop.core.mail_template.theme_catalog'
      $routing: '@router'
      $configuration: '@prestashop.adapter.legacy.configuration'
      $translator: '@translator'
    tags: ['form.type']

  PrestaShopBundle\Controller\Admin\Configure\ShopParameters\OrderStateController:
    class: 'PrestaShop\Module\OrderFeatures\Controller\Admin\Configure\ShopParameters\OrderStateControllerDecorator'
    autoconfigure: true
    autowire: true
    public: true
    tags: ['controller.service_arguments'] 

  prestashop.module.orderfeatures.adapter.order_state.command_handler.add_order_state:
    class: 'PrestaShop\Module\OrderFeatures\Adapter\OrderState\CommandHandler\AddOrderStateHandler'
    decorates: prestashop.adapter.order_state.command_handler.add_order_state
    autoconfigure: true
    arguments:
      - '@PrestaShop\PrestaShop\Adapter\File\Uploader\OrderStateFileUploader'

  prestashop.module.orderfeatures.adapter.order_state.query_handler.get_order_state_for_editing:
    class: 'PrestaShop\Module\OrderFeatures\Adapter\OrderState\QueryHandler\GetOrderStateForEditingHandler'
    decorates: prestashop.adapter.order_state.query_handler.get_order_state_for_editing
    autoconfigure: true

  prestashop.module.orderfeatures.adapter.order_state.command_handler.edit_order_state_handler:
    class: 'PrestaShop\Module\OrderFeatures\Adapter\OrderState\CommandHandler\EditOrderStateHandler'
    autoconfigure: true
    arguments:
      - '@PrestaShop\PrestaShop\Adapter\File\Uploader\OrderStateFileUploader'

  PrestaShop\Module\OrderFeatures\Form\IdentifiableObject\DataProvider\OrderStateFormDataProvider:
    class: 'PrestaShop\Module\OrderFeatures\Form\IdentifiableObject\DataProvider\OrderStateFormDataProvider'
    arguments:
      - '@prestashop.core.query_bus'

  prestashop.module.form.identifiable_object.builder.order_state_form_builder:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder'
    factory: [ '@prestashop.core.form.builder.form_builder_factory', 'create' ]
    arguments:
      - 'PrestaShopBundle\Form\Admin\Configure\ShopParameters\OrderStates\OrderStateType'
      - '@PrestaShop\Module\OrderFeatures\Form\IdentifiableObject\DataProvider\OrderStateFormDataProvider'
    tags: ['form.builder'] 

  prestashop.module.form.identifiable_object.data_handler.order_state_form_data_handler:
    class: 'PrestaShop\Module\OrderFeatures\Form\IdentifiableObject\DataHandler\OrderStateFormDataHandler'
    arguments:
      - '@prestashop.core.command_bus'

  prestashop.module.form.identifiable_object.handler.order_state_form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: [ '@prestashop.core.form.identifiable_object.handler.form_handler_factory', 'create' ]
    arguments:
      - '@prestashop.module.form.identifiable_object.data_handler.order_state_form_data_handler'

  PrestaShop\Module\OrderFeatures\Command\DeleteOrdersCommand:
    arguments:
      $commandBus: '@prestashop.core.command_bus'
    tags:
      - { name: 'console.command' }

